# -*- coding: utf-8 -*-
"""Friday14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXqQsc_1bFHmfsbfYtzCl4g0svXIUUW2
"""

# write a program to print first 10 natural numbers.
n=1
while n<=10:
  print(n)
  n+=1

# Write a program to find even numbers from 1 to 10.
e=2
while e<=10:
  print(e)
  e +=2

e=2
while e<=10 and e%2==0:
  print(e)
  e+=2

# functions declaration and calling
def Hello(): # declared
  print("Hello World!")
Hello() # called

# Function with return statement
def plus():
  a=int(input("Enter first number:"))
  b=int(input("Enter second number:"))
  return a+b
plus()

def cal():
  a=int(input("Enter a number:"))
  b=int(input("Enter second number:"))
  return a-b, a+b, a*b, a/b

cal()

def calculator():
  a=int(input("Enter a number:"))
  b=int(input("Enter second number:"))
  operation=input("Press the desired operator:")
  if operation=="+":
    return a+b
  elif operation=="-":
    return a-b
  elif operation=="*":
    return a*b
  elif operation=="/":
    return a/b
  else:
    print("Invalid Operator")

calculator()

def fun(a,b): # parameters i.e variables
  return a+b
fun(4,8) # arguments i.e values of the variables

def fun2(a=5,b=2):
  return a+b
fun2(2,3)

# string length
x="Sajeel Arshad"
print(len(x))  # len() length function