# -*- coding: utf-8 -*-
"""March17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nG2rpfEGWFHhRaXpYejR3I-I2Qrp7Qyx
"""

# Strings - Anything in the signle, double or triple quotes is considered as string
sq1 = 'This is single quote string'
print(sq1)

sq2 = "This is double quote string"
print(sq2)

sq3 = '''This is triple quote string'''
print(sq3)

# Indexing - Starts from left to right with 0 as left and from right to left with -1 as right
name = "Sajeel"
print(name[2])

name = "Sajeel"
print(name[0])

name = "Sajeel"
print(name[-1])

topic = "Data Analysis using Python"
print ("Initial String is: ")
print(topic)
print("\nFirst character of the string is: ")
print(topic[0])
print("\nLast character is: ")
print(topic[-1])

# Slicing in index is used to print some part of the string
crs = "Sajeel is learning Python"
print(crs[3:8]) # start from 3 and end at 7
print(crs[:-1]) # start from the very left and end at second last
print(crs[:13]) # start from the 0
print(crs[:]) # all the string is printed

# To print the string in reverse order
a = "Kingdom"
print(a[::-1])

# Step or skipping in string
a = "Commander"
print(a[2:7:2]) # starts from index 2 and ends at 6 and then prints next character after skipping 1 character

A = [1,2,3,4,5,6,7] # find index no
print(A.index(4))

a = 'Pakistan'
print(a.index('t'))