# -*- coding: utf-8 -*-
"""March18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YaGKPFFJILHLCMxnYShkNkIkNxnq2BP
"""

# String concatenation
a = "First"
b = "Program"
print(a+" "+b)

a = 'First'
b = 'Ten'
string3 = a + ' ' + b
print(string3)

bin(32)

# Finding index
list1 = ['physics', 'chemistry', 1997, 2000]
list1.index('chemistry')

list2 = [1,2,3,4,5]
list2.index(3)

list3 = ['a','b','c','d']
list3.index('d')

# Range of indexes
fruits = ["Apple", "Orange", "Banana", "Grapes"]
print(fruits[1:-1])