# -*- coding: utf-8 -*-
"""March19Wednesday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaG-OPaoVCl6qRuXUJ5NMTmdqgMGQ7kZ
"""

# List and its functions
# 1. append()
fruits = ['apple', 'banana', 'cherry']
fruits.append('orange') # append adds new item at the end of the list
print(fruits)

# 2. insert()
fruits = ['apple', 'banana', 'cherry']
fruits.insert(2,'Mango') # insert adds new item at a specific index
print(fruits)

# 3. extend()
fruits = ['apple', 'banana', 'cherry']
veg = ['potato', 'tomato']
fruits.extend(veg) # extend adds new list at the end of the list
print(fruits)

fruits = ['apple', 'banana', 'cherry']
veg = ('potato', 'tomato') # this is a tuple
fruits.extend(veg) # extend can also adds new tuple at the end of the list
print(fruits)

# 5. pop()
fruits = ['apple', 'banana', 'cherry']
fruits.pop(1) # pop removes the item at the specific index
print(fruits)

#  6. remove()
fruits = ['apple', 'banana', 'cherry']
fruits.remove('banana') # remove removes the item with the specific value
print(fruits)
fruits.clear

#  7. clear()
fruits = ['apple', 'banana', 'cherry']
fruits.clear() # clear removes all the items from the list
print(fruits)

#  8. del
fruits = ['apple', 'banana', 'cherry']
del fruits[1] # del deletes the item at the specific index
print(fruits)

# Sorting the list items
fruits = ['apple', 'Banana', 'cherry']
fruits.sort() # sort sorts the list items in ascending order according to the ASCII code
print(fruits)

l = [23,65,77,32,124,65,6]
l.sort() # sorts the items in ascending order
print(l)

fruits = ['apple', 'Banana', 'cherry']
fruits.sort(reverse=True) # sort sorts the list items in descending order according to the ASCII code
print(fruits)

l = [23,65,77,32,124,65,6]
l.sort(reverse=True) # sorts the items in descending order according to ASCII code
print(l)

# reverse the order of elements of the list
fruits = ['apple', 'banana', 'cherry']
fruits.reverse() # reverse the order of elements of the list
print(fruits)

# count()
l = [23,0,6,0,43,24,0,22]
l.count(0) # counts how many time an element is present

# copy()
names = ['sa', 'na', 'fa']
ss = names.copy() # copy creates a copy of the list
print(ss)

# joining two lists using operator +
alp = ["a", "b", "c"]
num = [1,2,3,4]
join = alp + num
print(join)

alp = ["a", "b", "c"]
num = [1,2,3,4]
alp.extend(num) # extend adds new list at the end of the list
print(alp)