# -*- coding: utf-8 -*-
"""Wednesday12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WR5_Cc_3-mYX9yMDlqWg-Qpl3rLPNgZ
"""

# For taking input from the user
x=int(input("Enter first number"))

y=int(input("Enter second number"))

print("Addition=", x+y)
print("Subtraction=",x-y)

# Assignment operator
x=43
x+=32
print(x)

x=33
x/=11
print(x)

x=45
x*=3
print(x)

x=23
x-=2
print(x)

x=45
x/=5
print(x)

# Comparison
x=6
y=8
print(x==y)

# Logical Operators
#AND, OR, NOT
#AND
x=3
print(x<45 and x>33)

#OR
x=23
print(x<34 or x>22)

#NOT
x=22
print(not(x<4 and x>3))

# Identity Operators
# is , is not
# is : same memory address
# is not: not same

# Membership operators
# in ,  not in
#in : value exists
# not in: does not exist

# Write a code for finding whether user is eligible for CNIC or Driving License.